future: true

# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          
paginate:       5
baseurl:        ""
url:            "http://devtalks.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Shalitha Suranga
  url:          http://devtalks.github.io
  email:        shalithasuranga@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
